/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author apriz
 */
public class CalculoPerimetro extends javax.swing.JInternalFrame {

    /**
     * Creates new form CalculoPerimetro
     */
    public CalculoPerimetro() {
        initComponents();
        this.setSize(500,400);
        this.setTitle("Perimetro y Area");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtParametro1 = new javax.swing.JTextField();
        txtParametro2 = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPerimetro = new javax.swing.JTextField();
        txtArea = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Primer Parametro");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setText("Segundo Parametro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        getContentPane().add(txtParametro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 110, -1));
        getContentPane().add(txtParametro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 110, -1));

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jLabel3.setText("Perimetro");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel4.setText("Area");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        txtPerimetro.setEditable(false);
        getContentPane().add(txtPerimetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 80, -1));

        txtArea.setEditable(false);
        getContentPane().add(txtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        String valor1,valor2;
        int num1,num2,perimetro,area;
        valor1 = txtParametro1.getText();
        valor2 = txtParametro2.getText();
        //calcular perimetro
        num1 = Integer.parseInt(valor1);
        num2 = Integer.parseInt(valor2);
        
        perimetro = num1 + num2 + num1 + num2;
        txtPerimetro.setText(Integer.toString(perimetro));
        
        //calcular Area
        area = num1 * num2;
        txtArea.setText(Integer.toString(area));
        txtParametro1.setText("");
        txtParametro2.setText("");
    }//GEN-LAST:event_btnGenerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtParametro1;
    private javax.swing.JTextField txtParametro2;
    private javax.swing.JTextField txtPerimetro;
    // End of variables declaration//GEN-END:variables
}
