/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author apriz
 */
public class Imprimir extends javax.swing.JInternalFrame {

    /**
     * Creates new form Imprimir
     */
    public Imprimir() {
        initComponents();
        this.setSize(400,300);
        this.setTitle("Imprimir palabras");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPalabra = new javax.swing.JLabel();
        txtPalabra = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPalabra.setText("Palabra");
        getContentPane().add(lblPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));
        getContentPane().add(txtPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 140, -1));

        lblNumero.setText("Numero");
        getContentPane().add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 140, -1));

        btnGenerar.setText("Imprimir Palabra");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        String palabra = txtPalabra.getText();
        String numero = txtNumero.getText();
        int numerofinal;
        
        numerofinal = Integer.parseInt(numero);
        
        for (int i = 0; i < numerofinal; i++) {
            //JOptionPane.showMessageDialog(null, palabra);
            System.out.println(palabra);
        }
    }//GEN-LAST:event_btnGenerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPalabra;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPalabra;
    // End of variables declaration//GEN-END:variables
}
