/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author apriz
 */
public class NumeroMayor extends javax.swing.JInternalFrame {

    /**
     * Creates new form NumeroMayor
     */
    public NumeroMayor() {
        initComponents();
        this.setSize(400, 300);
        this.setTitle("Identificar numero mayor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumero1 = new javax.swing.JTextField();
        txtNumero2 = new javax.swing.JTextField();
        txtNumero3 = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Primer numero");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setText("Segundo numero");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setText("Tercer numero");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        getContentPane().add(txtNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 110, -1));
        getContentPane().add(txtNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 110, -1));
        getContentPane().add(txtNumero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, -1));

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        String numero1, numero2, numero3;
        int num1, num2, num3, result;

        numero1 = txtNumero1.getText();
        numero2 = txtNumero2.getText();
        numero3 = txtNumero3.getText();
        num1 = Integer.parseInt(numero1);
        num2 = Integer.parseInt(numero2);
        num3 = Integer.parseInt(numero3);
        if (num1 == num2 && num2 == num3) {
            JOptionPane.showMessageDialog(null, "Los numero son iguales");
            txtNumero1.setText("");
            txtNumero2.setText("");
            txtNumero3.setText("");
        } else if (num1 > num2 && num1 > num3) {
            //txtResultado.setText(Integer.toString(num1));
            JOptionPane.showMessageDialog(null, "El numero mayor es: " + num1);
            txtNumero1.setText("");
            txtNumero2.setText("");
            txtNumero3.setText("");
        } else if (num2 > num1 && num2 > num3) {
            JOptionPane.showMessageDialog(null, "El numero mayor es: " + num2);
            txtNumero1.setText("");
            txtNumero2.setText("");
            txtNumero3.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "El numero mayor es: " + num3);
            txtNumero1.setText("");
            txtNumero2.setText("");
            txtNumero3.setText("");
        }
    }//GEN-LAST:event_btnGenerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    private javax.swing.JTextField txtNumero3;
    // End of variables declaration//GEN-END:variables
}
