/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author apriz
 */
public class OperacionesBacicas extends javax.swing.JInternalFrame {

    /**
     * Creates new form OperacionesBacicas
     */
    public OperacionesBacicas() {
        initComponents();
        this.setSize(400,300);
        this.setTitle("Operaciones basicas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumero1 = new javax.swing.JTextField();
        txtNumero2 = new javax.swing.JTextField();
        btnSuma = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        txtResultado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Primer Numero");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 24, -1, -1));

        jLabel2.setText("Segundo Numero");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        getContentPane().add(txtNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 100, -1));
        getContentPane().add(txtNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 100, -1));

        btnSuma.setText("Suma");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 80, -1));

        btnResta.setText("Restar");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        getContentPane().add(btnResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 80, -1));

        btnMultiplicar.setText("Multiplicar");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        btnDividir.setText("Dividir");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });
        getContentPane().add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 80, -1));
        getContentPane().add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 160, -1));

        jLabel3.setText("Resultado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        
        String NumeroUno,NumeroDos,resultado;
        int suma,num1,num2; 
        NumeroUno = txtNumero1.getText();
        NumeroDos = txtNumero2.getText();
        
        num1 = Integer.parseInt(NumeroUno);
        num2 = Integer.parseInt(NumeroDos);
        
        suma = num1 + num2;
        resultado = Integer.toString(suma);
        txtResultado.setText(resultado);
        txtNumero1.setText("");
        txtNumero2.setText("");    
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
       String NumeroUno,NumeroDos,resultado;
        int resta,num1,num2; 
        NumeroUno = txtNumero1.getText();
        NumeroDos = txtNumero2.getText();
        
        num1 = Integer.parseInt(NumeroUno);
        num2 = Integer.parseInt(NumeroDos);
        
        resta = num1 - num2;
        resultado = Integer.toString(resta);
        txtResultado.setText(resultado);
        txtNumero1.setText("");
        txtNumero2.setText(""); 
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        String NumeroUno,NumeroDos,resultado;
        int multiplicar,num1,num2; 
        NumeroUno = txtNumero1.getText();
        NumeroDos = txtNumero2.getText();
        
        num1 = Integer.parseInt(NumeroUno);
        num2 = Integer.parseInt(NumeroDos);
        
        multiplicar = num1 * num2;
        resultado = Integer.toString(multiplicar);
        txtResultado.setText(resultado);
        txtNumero1.setText("");
        txtNumero2.setText("");
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        String NumeroUno,NumeroDos,resultado;
        int num1,num2;
        double dividir;
        NumeroUno = txtNumero1.getText();
        NumeroDos = txtNumero2.getText();
        
        num1 = Integer.parseInt(NumeroUno);
        num2 = Integer.parseInt(NumeroDos);
        
        dividir = (double)num1 / (double)num2;
        
        //JOptionPane.showMessageDialog(null, dividir);
        resultado = Double.toString(dividir);
        txtResultado.setText(resultado);
        txtNumero1.setText("");
        txtNumero2.setText("");
    }//GEN-LAST:event_btnDividirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
