/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.JOptionPane;
import Interfaces.Nombre;
import Interfaces.Bienvenida;
/**
 *
 * @author apriz
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(600,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        opBienvenida = new javax.swing.JMenuItem();
        opNombres = new javax.swing.JMenuItem();
        opImprimirPalabra = new javax.swing.JMenuItem();
        opOperacionesBasicas = new javax.swing.JMenuItem();
        opNumeroMayor = new javax.swing.JMenuItem();
        opPerimetro = new javax.swing.JMenuItem();
        opCircunferencia = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 550));
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Escritorio.setPreferredSize(new java.awt.Dimension(600, 490));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIENVENIDO");

        Escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel1)
                .addContainerGap(243, Short.MAX_VALUE))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel1)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        getContentPane().add(Escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));

        jMenu3.setText("Eventos");

        opBienvenida.setText("Bienvenida");
        opBienvenida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opBienvenidaActionPerformed(evt);
            }
        });
        jMenu3.add(opBienvenida);

        opNombres.setText("Nombres");
        opNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opNombresActionPerformed(evt);
            }
        });
        jMenu3.add(opNombres);

        opImprimirPalabra.setText("Imprimir Palabra");
        opImprimirPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opImprimirPalabraActionPerformed(evt);
            }
        });
        jMenu3.add(opImprimirPalabra);

        opOperacionesBasicas.setText("Operaciones Basicas");
        opOperacionesBasicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opOperacionesBasicasActionPerformed(evt);
            }
        });
        jMenu3.add(opOperacionesBasicas);

        opNumeroMayor.setText("Numero mayor");
        opNumeroMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opNumeroMayorActionPerformed(evt);
            }
        });
        jMenu3.add(opNumeroMayor);

        opPerimetro.setText("Calculo perimetro");
        opPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opPerimetroActionPerformed(evt);
            }
        });
        jMenu3.add(opPerimetro);

        opCircunferencia.setText("Calculo circunferencia");
        opCircunferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opCircunferenciaActionPerformed(evt);
            }
        });
        jMenu3.add(opCircunferencia);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opNombresActionPerformed
       Nombre cargaNombre = new Nombre();
       Escritorio.add(cargaNombre);
       cargaNombre.show();
    }//GEN-LAST:event_opNombresActionPerformed

    private void opBienvenidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opBienvenidaActionPerformed
        Bienvenida well = new Bienvenida();
        Escritorio.add(well);
        well.show();
    }//GEN-LAST:event_opBienvenidaActionPerformed

    private void opImprimirPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opImprimirPalabraActionPerformed
        Imprimir print = new Imprimir();
        Escritorio.add(print);
        print.setVisible(true);
    }//GEN-LAST:event_opImprimirPalabraActionPerformed

    private void opOperacionesBasicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opOperacionesBasicasActionPerformed
        OperacionesBacicas basic = new OperacionesBacicas();
        Escritorio.add(basic);
        basic.setVisible(true);
    }//GEN-LAST:event_opOperacionesBasicasActionPerformed

    private void opNumeroMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opNumeroMayorActionPerformed
        NumeroMayor number = new NumeroMayor();
        Escritorio.add(number);
        number.setVisible(true);
    }//GEN-LAST:event_opNumeroMayorActionPerformed

    private void opPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opPerimetroActionPerformed
        CalculoPerimetro perimetro = new CalculoPerimetro();
        Escritorio.add(perimetro);
        perimetro.setVisible(true);
    }//GEN-LAST:event_opPerimetroActionPerformed

    private void opCircunferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opCircunferenciaActionPerformed
        CalculoCircuferencia circulo = new CalculoCircuferencia();
        Escritorio.add(circulo);
        circulo.setVisible(true);
    }//GEN-LAST:event_opCircunferenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem opBienvenida;
    private javax.swing.JMenuItem opCircunferencia;
    private javax.swing.JMenuItem opImprimirPalabra;
    private javax.swing.JMenuItem opNombres;
    private javax.swing.JMenuItem opNumeroMayor;
    private javax.swing.JMenuItem opOperacionesBasicas;
    private javax.swing.JMenuItem opPerimetro;
    // End of variables declaration//GEN-END:variables
}
